version: '3'

services: 
    http-server: 
        build: .
        command: npm run start
        ports: 
            - '8080:8080'
        environment: 
            NODE_ENV: 'production'
            HTTP_PORT: 8080